server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-catalog
  data:
    mongodb:
      username: 'usr-catalog'
      password: 'pwd-catalog'
      database: 'catalog'
      port: 27017
      host: localhost
  zipkin:
     baseUrl: http://localhost:9411/
     enabled: true
     sender:
       type: rabbit
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
        defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      catalog:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      catalog:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException