server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-serie
  data:
    mongodb:
      username: 'usr-serie'
      password: 'pwd-serie'
      database: 'serie'
      port: 27016
      host: localhost
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka