version: '3.9'
services:
  #Contenedor para BBDD MySQL para API Movie
  mysql-movie:
    image: mysql:5.7
    container_name: mysql-movie
    restart: always
    environment:
      MYSQL_DATABASE: 'movie'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3366:3306' # <Port exposed> : <Port running inside container>
    expose:
      - '3306'

#    healthcheck:
#      test: [ "CMD", "usr-netflix-mysql", "ping", "-ppwd-netflix-mysql", "--silent" ]
#      interval: 5s
#      timeout: 3s
#      retries: 10

  #Contenedor para BBDD MongoDB para API Serie
  mongo-serie:
    image: mongo
    container_name: mongo-serie
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'serie'
      MONGO_INITDB_ROOT_USERNAME: 'usr-serie'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-serie'
    ports:
      - 27016:27017
    expose:
      - 27016
    volumes:
      - ./mongo-serie-init.js:/docker-entrypoint-initdb.d/mongo-serie-init.js:ro

  #Contenedor para BBDD MongoDB para API Catalog
  mongo-catalog:
    image: mongo
    container_name: mongo-catalog
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'catalog'
      MONGO_INITDB_ROOT_USERNAME: 'usr-catalog'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-catalog'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-catalog-init.js:/docker-entrypoint-initdb.d/mongo-catalog-init.js:ro

  #Contenedor para Zipkin
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    expose:
      - 9411
    depends_on:
      - storage

  #Contenedor para BusyBox
  storage:
    image: busybox:1.31.0
    container_name: storage

  #Contenedor para RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
      - 5672